graphic:
  centre:
    - 3
  educational_form:
    - 1
    - 2
  course_year:
    - 1
    - 2
    - 3
    - 4
courses:
  all:
    - Компютърни системи
    - Компютърни архитектури
    - Висша математика ІІІ
    - Вероятности и статистика
    - Информационна сигурност
    - Кодиране и защита на информацията
